name = "modelscope"
main = "index.ts"
compatibility_date = "2025-05-30"
routes = [
  { pattern = "modelscope-proxy.zhangzhijia.online", custom_domain = true }
]

# Enable logging
[observability]
enabled = true
head_sampling_rate = 1
